"""Hybrid topology-first GSDM with fixed-topology categorical attribute diffusion.

The model combines the topology branch from the hierarchical attributed
Laplacian log-gap model with the iterative categorical attribute process from
GraphES' joint spectral/categorical implementation.

Design contract
---------------
* Binary topology A is generated first by combinatorial-Laplacian log-gap
  diffusion, supervised by topology-only connected induced graphlets and ORCA
  orbit summaries.
* Once decoded, A is frozen.  Attribute generation cannot add or remove edges.
* Atom categories and real bond categories are generated by an exact-terminal
  marginal categorical diffusion conditioned on A.
* Bond diffusion exists only on present unordered topology edges.  There is no
  learned or sampled ``no-edge`` bond category.
* Typed connected induced graphlets supervise only the attribute branch.
* The final reverse transition applies degree-compatible atom sampling and the
  joint valence-budgeted bond decoder.  This is an intrinsic endpoint
  transition, not RDKit repair, filtering, replacement sampling, or rewiring.
* Topology and attribute PPGN encoders are parameter-disjoint.
"""
from __future__ import annotations

import copy
import json
import math
import pickle
import shutil
import tempfile
import time
from collections import defaultdict
from collections.abc import Mapping
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import networkx as nx
import numpy as np
import torch
import torch.nn.functional as F
import yaml
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

from grapher.models.artifacts import ArtifactLayout
from grapher.models.base import GenerateRequest, GenerationArtifacts, TrainRequest, TrainingArtifacts
from grapher.models.errors import ArtifactCollisionError
from grapher.models.gdsm_simple.model import sinusoidal_time_embedding
from grapher.rewiring_mlp.attributed.data import GraphCategoryVocabulary

from . import hierarchical_attributed_loggap as hierarchical
from .attribute_decoding import (
    decoding_diagnostics,
    sample_atoms,
    sample_bonds,
    validate_decode_config,
)
from .categorical.noise import MarginalNoise, cosine_alpha_bar, draw_categories
from .vanilla_gsdm import (
    _EMA,
    _fit_laplacian_log_gap_stats,
    _laplacian_eigh_padded,
    _make_sdes,
    _operator_eigenvalues_to_spectral_state,
    _resolve_device,
    _seed_everything,
    _sha256,
    _spectral_state_to_operator_eigenvalues,
    _write_json,
    degree_features,
    eigen_mask_from_flags,
    mask_x,
    reconstruct_adjacency,
    sample_batch,
)


ATTRIBUTE_DIFFUSION_TRAINING_CONTRACT = "fixed_topology_marginal_attribute_diffusion_v1"
CHECKPOINT_FORMAT = "gdsm_simple_laplacian_loggap_hybrid_attributed_ppgn_v1"
TRAINING_FORMAT = "grapher_gdsm_simple_laplacian_loggap_hybrid_attributed_training_v1"
GENERATION_FORMAT = "grapher_gdsm_simple_laplacian_loggap_hybrid_attributed_generation_v1"
VARIANTS = {
    "vanilla_laplacian_loggap_hybrid_categorical_attributed_ppgn",
    "laplacian_loggap_hybrid_categorical_attributed_ppgn",
    "gsdm_laplacian_loggap_hybrid_categorical_attributed_ppgn",
    "topology_frozen_spectral_categorical_diffusion",
}


def default_options() -> dict[str, Any]:
    options = hierarchical.default_options()
    options["variant"] = "vanilla_laplacian_loggap_hybrid_categorical_attributed_ppgn"
    options["attribute_diffusion"] = {
        "enabled": True,
        "steps": 100,
        "sample_steps": 100,
        "noise": "marginal",
        "schedule": "cosine_exact_terminal",
        "pseudocount": 1.0e-3,
        "objective": "clean_endpoint_cross_entropy",
        "endpoint_constraint": "final_reverse_transition",
        "save_trajectory": False,
    }
    # Mask corruption belongs to the previous decoder and is intentionally not
    # part of this model.  The final endpoint policy remains configurable.
    options["attributed"].pop("corruption", None)
    options["attributed"]["decode"] = {
        "node_mode": "sample",
        "edge_mode": "sample",
        "node_temperature": 1.0,
        "edge_temperature": 0.6,
        "constraint_mode": "atom_bond_valence",
        "edge_order": "random",
        "infeasible_policy": "retain",
    }
    return options


def _deep_update(base: dict[str, Any], changes: Mapping[str, Any]) -> dict[str, Any]:
    return hierarchical._deep_update(base, changes)


def validate_options(options: Mapping[str, Any]) -> None:
    variant = str(options.get("variant", "")).lower()
    if variant not in VARIANTS:
        raise ValueError(
            "Hybrid attributed pipeline requires "
            "vanilla_laplacian_loggap_hybrid_categorical_attributed_ppgn"
        )
    # Reuse all topology, summary, vocabulary, and endpoint validation from the
    # hierarchical model under its canonical variant name.
    hierarchical_options = copy.deepcopy(dict(options))
    hierarchical_options["variant"] = "vanilla_laplacian_loggap_hierarchical_attributed_ppgn"
    hierarchical_options.setdefault("attributed", {}).setdefault(
        "corruption",
        {
            "mask_probability_min": 0.15,
            "mask_probability_max": 0.95,
            "full_mask_probability": 0.25,
        },
    )
    hierarchical.validate_options(hierarchical_options)

    cfg = dict(options.get("attribute_diffusion", {}) or {})
    allowed = {
        "enabled", "steps", "sample_steps", "noise", "schedule", "pseudocount",
        "objective", "endpoint_constraint", "save_trajectory",
    }
    unknown = sorted(set(cfg) - allowed)
    if unknown:
        raise ValueError(f"Unknown attribute_diffusion settings: {unknown}")
    if not bool(cfg.get("enabled", False)):
        raise ValueError("attribute_diffusion.enabled must be true")
    steps = int(cfg.get("steps", 0))
    sample_steps = int(cfg.get("sample_steps", steps))
    if steps < 2:
        raise ValueError("attribute_diffusion.steps must be >= 2")
    if sample_steps < 1 or sample_steps > steps:
        raise ValueError("attribute_diffusion.sample_steps must be in [1, steps]")
    if str(cfg.get("noise", "marginal")) != "marginal":
        raise ValueError("Hybrid attributes use marginal categorical noise only")
    if str(cfg.get("schedule", "cosine_exact_terminal")) != "cosine_exact_terminal":
        raise ValueError("Hybrid attributes require cosine_exact_terminal")
    pseudocount = float(cfg.get("pseudocount", 0.0))
    if not math.isfinite(pseudocount) or pseudocount <= 0:
        raise ValueError("attribute_diffusion.pseudocount must be finite and > 0")
    if str(cfg.get("objective", "")) != "clean_endpoint_cross_entropy":
        raise ValueError("Hybrid attributes use clean_endpoint_cross_entropy")
    if str(cfg.get("endpoint_constraint", "")) != "final_reverse_transition":
        raise ValueError("Chemical constraints are applied in the final reverse transition")
    if bool((options.get("graphlet_refinement", {}) or {}).get("enabled", False)):
        raise ValueError("Hybrid attributed generation does not use rewiring")


def _model_config(
    options: Mapping[str, Any], max_nodes: int, vocab: GraphCategoryVocabulary
) -> dict[str, Any]:
    result = hierarchical._model_config(options, max_nodes, vocab)
    result["attribute_time_conditioning"] = True
    return result


class HybridAttributedSpectrumPPGNScore(hierarchical.AttributedSpectrumPPGNScore):
    """Separate topology PPGN and time-conditioned fixed-topology attribute PPGN."""

    def __init__(self, *args: Any, attribute_time_conditioning: bool = True, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        if not attribute_time_conditioning:
            raise ValueError("Hybrid attribute diffusion requires explicit time conditioning")

        # The hierarchical predecessor reserves an extra MASK channel.  Marginal
        # diffusion has only real categories at every state, so rebuild the
        # attribute input projection without a mask/no-edge channel.
        self.node_input_classes = self.node_classes
        self.edge_input_classes = self.edge_classes
        topology_node_dim = self.max_feat_num + self.rw_steps
        attribute_node_dim = topology_node_dim + self.node_input_classes
        attribute_pair_dim = 2 + self.sp_dim + attribute_node_dim + self.edge_input_classes
        self.attribute_pair_input = nn.Linear(attribute_pair_dim, self.ppgn_hidden_dim)
        self.attribute_pair_input_norm = nn.LayerNorm(self.ppgn_hidden_dim)
        self.attribute_time_mlp = nn.Sequential(
            nn.Linear(self.ppgn_hidden_dim, self.ppgn_hidden_dim),
            nn.SiLU(),
            nn.Linear(self.ppgn_hidden_dim, self.ppgn_hidden_dim),
        )

    def attribute_parameters(self):
        yield from super().attribute_parameters()
        yield from self.attribute_time_mlp.parameters()

    def categorical_attribute_inputs(
        self,
        flags: torch.Tensor,
        support: torch.Tensor,
        node_state: torch.Tensor,
        edge_state: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        b, n = flags.shape
        if node_state.shape != (b, n):
            raise ValueError("node_state must have shape [B,N]")
        if edge_state.shape != (b, n, n):
            raise ValueError("edge_state must have shape [B,N,N]")
        active = flags.bool()
        if support.dtype != torch.bool or support.shape != edge_state.shape:
            raise ValueError("support must be boolean [B,N,N]")
        if not torch.equal(support, support.transpose(1, 2)):
            raise ValueError("fixed topology support must be symmetric")
        eye = torch.eye(n, dtype=torch.bool, device=flags.device).unsqueeze(0)
        valid_pairs = active.unsqueeze(1) & active.unsqueeze(2) & ~eye
        if bool((support & ~valid_pairs).any()):
            raise ValueError("fixed topology support contains padded pairs or loops")
        if bool(((node_state < 0) | (node_state >= self.node_classes))[active].any()):
            raise ValueError("node_state contains an out-of-vocabulary category")
        if bool(((edge_state < 0) | (edge_state >= self.edge_classes))[support].any()):
            raise ValueError("edge_state contains an out-of-vocabulary bond category")

        node_attr = F.one_hot(
            node_state.clamp(min=0, max=self.node_classes - 1), self.node_classes
        ).to(flags.dtype)
        node_attr = node_attr * active.unsqueeze(-1).to(node_attr.dtype)
        edge_attr = F.one_hot(
            edge_state.clamp(min=0, max=self.edge_classes - 1), self.edge_classes
        ).to(flags.dtype)
        edge_attr = edge_attr * support.unsqueeze(-1).to(edge_attr.dtype)
        return node_attr, edge_attr

    def _encode_attributes(
        self,
        x: torch.Tensor,
        adj: torch.Tensor,
        flags: torch.Tensor,
        eigenvalues: torch.Tensor,
        *,
        node_attr: torch.Tensor | None = None,
        edge_attr: torch.Tensor | None = None,
        attribute_time: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        if node_attr is None or edge_attr is None:
            raise ValueError("Hybrid attribute diffusion requires explicit categorical states")
        if attribute_time is None or attribute_time.shape != (flags.shape[0],):
            raise ValueError("attribute_time must have shape [B]")
        binary, node, _sp, base = self._base_parts(x, adj, flags)
        node = torch.cat((node, node_attr), dim=-1)
        pair = torch.cat((base, self._diag_pair(node), edge_attr), dim=-1)
        pair_mask = flags.to(pair.dtype).unsqueeze(-1) * flags.to(pair.dtype).unsqueeze(-2)
        h = F.elu(self.attribute_pair_input_norm(self.attribute_pair_input(pair)))
        time_context = self.attribute_time_mlp(
            sinusoidal_time_embedding(attribute_time.float(), self.ppgn_hidden_dim)
        )
        h = (h + time_context[:, None, None, :]) * pair_mask.unsqueeze(-1)
        for layer in self.attribute_ppgn_layers:
            h = layer(h, pair_mask, flags)
        shared, _ = self._pool_pair(h, flags, eigenvalues)
        return shared, h, binary

    def forward_attributes(
        self,
        x: torch.Tensor,
        adj: torch.Tensor,
        flags: torch.Tensor,
        eigenvectors: torch.Tensor,
        eigenvalues: torch.Tensor,
        *,
        node_attr: torch.Tensor | None = None,
        edge_attr: torch.Tensor | None = None,
        attribute_time: torch.Tensor | None = None,
    ) -> dict[str, torch.Tensor]:
        del eigenvectors
        shared, pair_h, _binary = self._encode_attributes(
            x,
            adj,
            flags,
            eigenvalues,
            node_attr=node_attr,
            edge_attr=edge_attr,
            attribute_time=attribute_time,
        )
        n = pair_h.size(1)
        idx = torch.arange(n, device=pair_h.device)
        diag = pair_h[:, idx, idx, :]
        sym_pair = 0.5 * (pair_h + pair_h.transpose(1, 2))
        outputs = {
            "typed_graphlet_logits": self.typed_graphlet_logits(shared),
            "typed_graphlet_mass_logits": self.typed_graphlet_mass_logits(shared),
            "node_logits": self.node_category_head(diag),
            "edge_logits": self.edge_category_head(sym_pair),
        }
        for name, value in outputs.items():
            if not torch.isfinite(value).all():
                raise FloatingPointError(f"Non-finite {name} from hybrid attribute PPGN")
        return outputs


def _fit_attribute_diffusion_schema(
    node_labels: torch.Tensor,
    edge_labels: torch.Tensor,
    *,
    node_classes: int,
    edge_classes: int,
    pseudocount: float,
) -> dict[str, Any]:
    node_valid = node_labels >= 0
    node_counts = torch.bincount(
        node_labels[node_valid], minlength=int(node_classes)
    ).to(torch.float64)
    n = edge_labels.shape[1]
    upper = torch.triu(
        torch.ones((n, n), dtype=torch.bool, device=edge_labels.device), diagonal=1
    ).unsqueeze(0)
    edge_valid = (edge_labels >= 0) & upper
    edge_counts = torch.bincount(
        edge_labels[edge_valid], minlength=int(edge_classes)
    ).to(torch.float64)
    node_smoothed = node_counts + float(pseudocount)
    edge_smoothed = edge_counts + float(pseudocount)
    return {
        "node_category_counts": node_counts.to(torch.long).tolist(),
        "bond_category_counts": edge_counts.to(torch.long).tolist(),
        "node_marginal": (node_smoothed / node_smoothed.sum()).tolist(),
        "bond_marginal": (edge_smoothed / edge_smoothed.sum()).tolist(),
        "bond_head_includes_no_edge": False,
        "bond_domain": "clean_present_unordered_topology_edges_only",
        "source": "training_split_only",
    }


def _attribute_noise_models(
    schema: Mapping[str, Any], cfg: Mapping[str, Any], device: torch.device
) -> tuple[torch.Tensor, MarginalNoise, MarginalNoise]:
    schedule = cosine_alpha_bar(int(cfg["steps"]), device=device)
    return (
        schedule,
        MarginalNoise(schema["node_marginal"], schedule),
        MarginalNoise(schema["bond_marginal"], schedule),
    )


def _sample_upper_categories(
    probabilities: torch.Tensor,
    support: torch.Tensor,
    generator: torch.Generator,
) -> torch.Tensor:
    if probabilities.shape[:-1] != support.shape:
        raise ValueError("Probability and fixed-support shapes differ")
    result = torch.zeros_like(support, dtype=torch.long)
    upper = support & torch.ones_like(support).triu(1)
    if bool(upper.any()):
        sampled = draw_categories(probabilities[upper], generator)
        result[upper] = sampled
        result = result + result.transpose(1, 2)
    return result


def _draw_noisy_attributes(
    node_labels: torch.Tensor,
    edge_labels: torch.Tensor,
    flags: torch.Tensor,
    support: torch.Tensor,
    t: torch.Tensor,
    node_noise: MarginalNoise,
    bond_noise: MarginalNoise,
    generator: torch.Generator,
) -> tuple[torch.Tensor, torch.Tensor]:
    node_probs = node_noise.forward_probs(node_labels.clamp_min(0), t)
    nodes = draw_categories(node_probs, generator).masked_fill(~flags.bool(), 0)
    bond_probs = bond_noise.forward_probs(edge_labels.clamp_min(0), t)
    bonds = _sample_upper_categories(bond_probs, support, generator)
    return nodes, bonds


def _categorical_diffusion_loss(
    outputs: Mapping[str, torch.Tensor],
    node_labels: torch.Tensor,
    edge_labels: torch.Tensor,
    flags: torch.Tensor,
    support: torch.Tensor,
) -> tuple[torch.Tensor, torch.Tensor, dict[str, float]]:
    node_selected = flags.bool() & (node_labels >= 0)
    upper = support & torch.ones_like(support).triu(1)

    def selected_loss(logits: torch.Tensor, labels: torch.Tensor, selected: torch.Tensor):
        if bool(selected.any()):
            loss = F.cross_entropy(logits[selected], labels[selected])
            accuracy = (logits[selected].argmax(-1) == labels[selected]).float().mean()
            return loss, float(accuracy.detach())
        return logits.sum() * 0.0, 0.0

    node_ce, node_accuracy = selected_loss(
        outputs["node_logits"], node_labels, node_selected
    )
    edge_ce, edge_accuracy = selected_loss(
        outputs["edge_logits"], edge_labels, upper
    )
    return node_ce, edge_ce, {
        "node_accuracy": node_accuracy,
        "edge_accuracy": edge_accuracy,
        "node_supervised_count": float(node_selected.sum()),
        "edge_supervised_count": float(upper.sum()),
    }


def _loss_batch(
    model_x,
    model_lam: HybridAttributedSpectrumPPGNScore,
    batch: tuple[torch.Tensor, ...],
    *,
    sde_x,
    sde_lam,
    eps: float,
    eigen_mask_mode: str,
    spectral_transform: Mapping[str, Any],
    topology_summary_cfg: Mapping[str, Any],
    attribute_summary_cfg: Mapping[str, Any],
    attr_cfg: Mapping[str, Any],
    attribute_diffusion_cfg: Mapping[str, Any],
    node_noise: MarginalNoise,
    bond_noise: MarginalNoise,
    generator: torch.Generator,
) -> tuple[torch.Tensor, dict[str, float]]:
    (
        x0,
        adj0,
        flags,
        _sizes,
        u,
        lam0,
        node_labels,
        edge_labels,
        topology_gh,
        topology_gm,
        topology_ch,
        topology_oh,
        topology_ot,
        typed_gh,
        typed_gm,
    ) = batch
    b = x0.size(0)
    state0 = _operator_eigenvalues_to_spectral_state(
        lam0,
        flags,
        spectral_operator="combinatorial_laplacian",
        spectral_transform=spectral_transform,
    )

    # Continuous topology diffusion branch.
    topology_t = torch.rand((b,), device=x0.device, generator=generator) * (1 - eps) + eps
    zx = mask_x(
        torch.randn(x0.shape, device=x0.device, generator=generator), flags
    )
    eigen_mask = eigen_mask_from_flags(flags, eigen_mask_mode)
    zs = torch.randn(state0.shape, device=x0.device, generator=generator) * eigen_mask
    mean_x, std_x = sde_x.marginal_x(x0, topology_t)
    xt = mask_x(mean_x + std_x[:, None, None] * zx, flags)
    mean_s, std_s = sde_lam.marginal_spectrum(state0, topology_t)
    st = (mean_s * eigen_mask + std_s[:, None] * zs) * eigen_mask
    lam_t = _spectral_state_to_operator_eigenvalues(
        st,
        flags,
        spectral_operator="combinatorial_laplacian",
        spectral_transform=spectral_transform,
    )
    operator_t = reconstruct_adjacency(u, lam_t)
    adj_t = hierarchical._operator_to_adjacency_state(
        operator_t, flags, "combinatorial_laplacian"
    )
    pred_x = model_x(xt, adj_t, flags, u, st)
    topology_out = model_lam.forward_topology(xt, adj_t, flags, u, st)

    # Fixed clean topology attribute diffusion branch.  The support comes from
    # clean present bonds and must match the clean binary topology exactly.
    n = adj0.size(1)
    eye = torch.eye(n, dtype=torch.bool, device=adj0.device).unsqueeze(0)
    clean_binary = (
        (adj0 > 0.5)
        & flags.bool().unsqueeze(1)
        & flags.bool().unsqueeze(2)
        & ~eye
    )
    clean_binary = clean_binary | clean_binary.transpose(1, 2)
    support = edge_labels >= 0
    if not torch.equal(support, clean_binary):
        raise AssertionError("Clean bond labels and topology support differ")
    total_attr_steps = int(attribute_diffusion_cfg["steps"])
    attribute_t = torch.randint(
        1,
        total_attr_steps + 1,
        (b,),
        device=x0.device,
        generator=generator,
    )
    noisy_nodes, noisy_bonds = _draw_noisy_attributes(
        node_labels,
        edge_labels,
        flags,
        support,
        attribute_t,
        node_noise,
        bond_noise,
        generator,
    )
    node_in, edge_in = model_lam.categorical_attribute_inputs(
        flags, support, noisy_nodes, noisy_bonds
    )
    attribute_out = model_lam.forward_attributes(
        x0,
        clean_binary.to(adj0.dtype),
        flags,
        u,
        state0,
        node_attr=node_in,
        edge_attr=edge_in,
        attribute_time=attribute_t.to(torch.float32) / float(total_attr_steps),
    )

    loss_x = 0.5 * (pred_x - zx).square().reshape(b, -1).sum(dim=-1).mean()
    loss_spectrum = 0.5 * (
        ((topology_out["spectrum"] - zs) * eigen_mask)
        .square()
        .reshape(b, -1)
        .sum(dim=-1)
    ).mean()
    topology_loss, metrics = hierarchical._topology_structure_loss(
        model_lam,
        topology_out,
        topology_gh,
        topology_gm,
        topology_ch,
        topology_oh,
        topology_ot,
        topology_summary_cfg,
    )
    typed_loss, typed_metrics = hierarchical._typed_graphlet_loss(
        model_lam,
        attribute_out,
        typed_gh,
        typed_gm,
        attribute_summary_cfg,
    )
    metrics.update(typed_metrics)
    node_ce, edge_ce, categorical_metrics = _categorical_diffusion_loss(
        attribute_out,
        node_labels,
        edge_labels,
        flags,
        support,
    )
    metrics.update(categorical_metrics)
    total = (
        loss_x
        + loss_spectrum
        + float(topology_summary_cfg.get("loss_weight", 0.10)) * topology_loss
        + float(attribute_summary_cfg.get("loss_weight", 0.10)) * typed_loss
        + float(attr_cfg.get("node_loss_weight", 1.0)) * node_ce
        + float(attr_cfg.get("edge_loss_weight", 1.0)) * edge_ce
    )
    metrics.update({
        "loss_x": float(loss_x.detach()),
        "loss_spectrum": float(loss_spectrum.detach()),
        "topology_structure_loss": float(topology_loss.detach()),
        "attribute_typed_graphlet_loss": float(typed_loss.detach()),
        "node_ce": float(node_ce.detach()),
        "edge_ce": float(edge_ce.detach()),
        "attribute_time_mean": float(attribute_t.float().mean().detach()),
        "attribute_time_fraction_mean": float(
            (attribute_t.float() / float(total_attr_steps)).mean().detach()
        ),
    })
    return total, metrics


def _build_models(
    model_cfg: Mapping[str, Any],
    topology_meta: Mapping[str, Any],
    attribute_meta: Mapping[str, Any],
    device: torch.device,
):
    structural_features = copy.deepcopy(
        dict(model_cfg.get("structural_features", {}) or {})
    )
    model_x = hierarchical.GSDMNodeScore(
        max_feat_num=int(model_cfg["max_feat_num"]),
        hidden_dim=int(model_cfg["hidden_dim"]),
        depth=int(model_cfg["depth"]),
        structural_features=structural_features,
    ).to(device)
    model_lam = HybridAttributedSpectrumPPGNScore(
        **dict(model_cfg),
        topology_graphlet_slices=tuple(
            tuple(int(v) for v in pair)
            for pair in topology_meta["graphlet_slices"]
        ),
        typed_graphlet_slices=tuple(
            tuple(int(v) for v in pair)
            for pair in attribute_meta["graphlet_slices"]
        ),
        topology_clustering_bins=(
            int(topology_meta["clustering_bins"])
            if topology_meta.get("clustering_enabled") else 0
        ),
        topology_orbit_width=(
            int(topology_meta["orbit_width"])
            if topology_meta.get("orbit_enabled") else 0
        ),
    ).to(device)
    return model_x, model_lam


def _artifacts(wrapper, request: TrainRequest) -> TrainingArtifacts:
    return hierarchical._artifacts(wrapper, request)


def train(
    wrapper, request: TrainRequest, options: Mapping[str, Any]
) -> TrainingArtifacts:
    validate_options(options)
    if request.run.dataset_id not in {"qm9", "zinc", "attributed"}:
        raise ValueError("Hybrid attributed pipeline is for attributed/molecular datasets")
    layout = request.run.layout
    artifacts = _artifacts(wrapper, request)
    fingerprint = request.dataset.fingerprint()
    if layout.training_manifest_path.is_file() and not request.overwrite:
        old = json.loads(layout.training_manifest_path.read_text())
        if (
            old.get("attribute_diffusion_training_contract")
            == ATTRIBUTE_DIFFUSION_TRAINING_CONTRACT
            and old.get("dataset", {}).get("fingerprint") == fingerprint
            and old.get("options") == hierarchical._jsonable(options)
            and artifacts.checkpoint_path.is_file()
        ):
            return artifacts
        raise ArtifactCollisionError(
            "Existing hybrid attributed run differs; choose a new run-id or --overwrite"
        )
    ArtifactLayout.require_available(layout.train_dir, overwrite=request.overwrite)
    _seed_everything(request.run.train_seed)
    device = _resolve_device(options.get("runtime", {}))
    started = time.monotonic()
    prep_started = time.monotonic()
    print("[hybrid-preprocess] loading train/validation molecular graphs...", flush=True)
    train_graphs = hierarchical._attributed_graphs(request.dataset.split_paths["train"])
    val_graphs = hierarchical._attributed_graphs(request.dataset.split_paths["val"])
    print(
        f"[hybrid-preprocess] loaded train={len(train_graphs)} val={len(val_graphs)} graphs",
        flush=True,
    )
    for split, graphs in (("train", train_graphs), ("val", val_graphs)):
        for index, graph in enumerate(graphs):
            if not nx.is_connected(graph):
                raise ValueError(
                    f"Hybrid attributed model requires connected graphs; found {split}[{index}]"
                )
    attr_cfg = dict(options["attributed"])
    vocab = GraphCategoryVocabulary.from_graphs(train_graphs, attr_cfg)
    max_nodes = int(
        options["model"].get("max_nodes")
        or max(graph.number_of_nodes() for graph in train_graphs)
    )
    if max(graph.number_of_nodes() for graph in val_graphs) > max_nodes:
        raise ValueError("Validation graph exceeds model.max_nodes")
    model_cfg = _model_config(options, max_nodes, vocab)
    print("[hybrid-preprocess] building padded Laplacian/eigenbasis tensors...", flush=True)
    stage = time.monotonic()
    train_base = hierarchical._padded_dataset(
        train_graphs,
        max_nodes=max_nodes,
        max_feat_num=model_cfg["max_feat_num"],
        spectral_operator="combinatorial_laplacian",
    )
    val_base = hierarchical._padded_dataset(
        val_graphs,
        max_nodes=max_nodes,
        max_feat_num=model_cfg["max_feat_num"],
        spectral_operator="combinatorial_laplacian",
    )
    print(
        f"[hybrid-preprocess] spectral tensors complete in {time.monotonic()-stage:.1f}s",
        flush=True,
    )
    train_labels = hierarchical._attributed_labels(train_graphs, vocab, max_nodes)
    val_labels = hierarchical._attributed_labels(val_graphs, vocab, max_nodes)
    diffusion_cfg = copy.deepcopy(dict(options["attribute_diffusion"]))
    diffusion_schema = _fit_attribute_diffusion_schema(
        train_labels[0],
        train_labels[1],
        node_classes=vocab.num_node_categories,
        edge_classes=len(vocab.edge_values),
        pseudocount=float(diffusion_cfg["pseudocount"]),
    )

    preprocess_cfg = dict(options.get("preprocess", {}) or {})
    cache_enabled = bool(preprocess_cfg.get("cache_structure_targets", True))
    cache_path = hierarchical._structure_cache_path(
        layout, fingerprint, options, vocab, max_nodes
    )
    loaded_cache = False
    if cache_enabled and cache_path.is_file():
        try:
            cached = hierarchical._torch_load_unrestricted(cache_path)
            if cached.get("format") == "gdsm_hierarchical_attr_structure_cache_v3":
                train_targets = tuple(cached["train_targets"])
                val_targets = tuple(cached["val_targets"])
                topology_basis = cached["topology_basis"]
                typed_basis = cached["typed_basis"]
                topology_meta = dict(cached["topology_meta"])
                attribute_meta = dict(cached["attribute_meta"])
                val_topology_meta = dict(cached["val_topology_meta"])
                val_attribute_meta = dict(cached["val_attribute_meta"])
                loaded_cache = True
                print(
                    f"[hybrid-preprocess] loaded cached hierarchical structure targets: {cache_path}",
                    flush=True,
                )
        except Exception as exc:
            print(
                f"[hybrid-preprocess] ignoring unreadable cache {cache_path}: "
                f"{type(exc).__name__}: {exc}",
                flush=True,
            )
    if not loaded_cache:
        (
            train_targets,
            topology_basis,
            typed_basis,
            topology_meta,
            attribute_meta,
        ) = hierarchical._hierarchical_structure_targets(
            train_graphs, options, vocab, seed=request.run.train_seed
        )
        (
            val_targets,
            _,
            _,
            val_topology_meta,
            val_attribute_meta,
        ) = hierarchical._hierarchical_structure_targets(
            val_graphs,
            options,
            vocab,
            topology_basis=topology_basis,
            typed_basis=typed_basis,
            seed=request.run.train_seed + 1,
        )
        if cache_enabled:
            cache_path.parent.mkdir(parents=True, exist_ok=True)
            temp = cache_path.with_suffix(cache_path.suffix + ".tmp")
            torch.save(
                {
                    "format": "gdsm_hierarchical_attr_structure_cache_v3",
                    "train_targets": tuple(t.cpu() for t in train_targets),
                    "val_targets": tuple(t.cpu() for t in val_targets),
                    "topology_basis": topology_basis,
                    "typed_basis": typed_basis,
                    "topology_meta": topology_meta,
                    "attribute_meta": attribute_meta,
                    "val_topology_meta": val_topology_meta,
                    "val_attribute_meta": val_attribute_meta,
                },
                temp,
            )
            temp.replace(cache_path)
            print(
                f"[hybrid-preprocess] cached hierarchical structure targets: {cache_path}",
                flush=True,
            )
    if val_topology_meta["graphlet_slices"] != topology_meta["graphlet_slices"]:
        raise AssertionError("Topology graphlet basis mismatch")
    if val_attribute_meta["graphlet_slices"] != attribute_meta["graphlet_slices"]:
        raise AssertionError("Typed graphlet basis mismatch")
    print(
        f"[hybrid-preprocess] all preprocessing complete in {time.monotonic()-prep_started:.1f}s; "
        "starting optimization",
        flush=True,
    )

    stats = _fit_laplacian_log_gap_stats(
        train_base[5],
        train_base[2],
        epsilon=float(options["sde"].get("log_gap_epsilon", 1e-6)),
        min_std=float(options["sde"].get("log_gap_min_std", 1e-3)),
    )
    spectral_transform = {
        "kind": "laplacian_log_gap",
        "epsilon": float(options["sde"].get("log_gap_epsilon", 1e-6)),
        "exp_clip": float(options["sde"].get("log_gap_exp_clip", 20)),
        "mean": stats["mean"],
        "std": stats["std"],
        "count": stats["count"],
    }
    train_data = (*train_base, *train_labels, *train_targets)
    val_data = (*val_base, *val_labels, *val_targets)
    train_loader = DataLoader(
        TensorDataset(*train_data),
        batch_size=int(options["train"]["batch_size"]),
        shuffle=True,
    )
    val_loader = DataLoader(
        TensorDataset(*val_data),
        batch_size=int(options["train"]["batch_size"]),
        shuffle=False,
    )
    model_x, model_lam = _build_models(model_cfg, topology_meta, attribute_meta, device)
    sde_x, sde_lam = _make_sdes(options, device)
    _, node_noise, bond_noise = _attribute_noise_models(
        diffusion_schema, diffusion_cfg, device
    )
    train_cfg = dict(options["train"])
    optimizer_x = torch.optim.Adam(
        model_x.parameters(),
        lr=float(train_cfg.get("node_lr", train_cfg["lr"])),
        weight_decay=float(train_cfg.get("weight_decay", 0)),
    )
    optimizer_lam = torch.optim.Adam(
        model_lam.parameters(),
        lr=float(train_cfg.get("spectrum_lr", train_cfg["lr"])),
        weight_decay=float(train_cfg.get("weight_decay", 0)),
    )
    schedulers = [
        torch.optim.lr_scheduler.ExponentialLR(
            optimizer, gamma=float(train_cfg.get("lr_decay", 1))
        )
        for optimizer in (optimizer_x, optimizer_lam)
    ]
    ema_x = _EMA(model_x, float(train_cfg.get("ema", 0.999)))
    ema_lam = _EMA(model_lam, float(train_cfg.get("ema", 0.999)))
    history: list[dict[str, Any]] = []
    epochs = int(train_cfg["epochs"])
    eps = float(options["sde"].get("eps", 1e-5))
    eigen_mask_mode = str(
        options["sde"].get("eigen_mask", "laplacian_nonzero_prefix")
    )
    layout.train_dir.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(
        tempfile.mkdtemp(prefix=".gdsm_hybrid_attr_train_", dir=layout.train_dir.parent)
    )
    (staging / "checkpoints").mkdir(parents=True, exist_ok=True)
    log_path = staging / "train.log"
    generator = torch.Generator(device=device).manual_seed(request.run.train_seed + 1729)
    try:
        with log_path.open("w") as log:
            for epoch in range(1, epochs + 1):
                model_x.train()
                model_lam.train()
                sums: defaultdict[str, float] = defaultdict(float)
                count = 0
                for raw in train_loader:
                    batch = tuple(value.to(device) for value in raw)
                    loss, parts = _loss_batch(
                        model_x,
                        model_lam,
                        batch,
                        sde_x=sde_x,
                        sde_lam=sde_lam,
                        eps=eps,
                        eigen_mask_mode=eigen_mask_mode,
                        spectral_transform=spectral_transform,
                        topology_summary_cfg=hierarchical._topology_summary_config(options),
                        attribute_summary_cfg=hierarchical._attribute_summary_config(options),
                        attr_cfg=attr_cfg,
                        attribute_diffusion_cfg=diffusion_cfg,
                        node_noise=node_noise,
                        bond_noise=bond_noise,
                        generator=generator,
                    )
                    if not torch.isfinite(loss):
                        raise FloatingPointError("Nonfinite hybrid attributed training loss")
                    optimizer_x.zero_grad(set_to_none=True)
                    optimizer_lam.zero_grad(set_to_none=True)
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(
                        model_x.parameters(), float(train_cfg.get("grad_norm", 1))
                    )
                    torch.nn.utils.clip_grad_norm_(
                        model_lam.parameters(), float(train_cfg.get("grad_norm", 1))
                    )
                    optimizer_x.step()
                    optimizer_lam.step()
                    ema_x.update(model_x)
                    ema_lam.update(model_lam)
                    batch_size = batch[0].size(0)
                    sums["loss"] += float(loss.detach()) * batch_size
                    for key, value in parts.items():
                        sums[key] += float(value) * batch_size
                    count += batch_size
                row = {
                    "epoch": epoch,
                    **{f"train_{key}": value / max(count, 1) for key, value in sums.items()},
                }
                if (
                    epoch == 1
                    or epoch % int(train_cfg.get("validation_every", 1)) == 0
                    or epoch == epochs
                ):
                    model_x.eval()
                    model_lam.eval()
                    validation_sums: defaultdict[str, float] = defaultdict(float)
                    validation_count = 0
                    validation_generator = torch.Generator(device=device).manual_seed(
                        request.run.train_seed + 100003 + epoch
                    )
                    with torch.no_grad():
                        for raw in val_loader:
                            batch = tuple(value.to(device) for value in raw)
                            loss, parts = _loss_batch(
                                model_x,
                                model_lam,
                                batch,
                                sde_x=sde_x,
                                sde_lam=sde_lam,
                                eps=eps,
                                eigen_mask_mode=eigen_mask_mode,
                                spectral_transform=spectral_transform,
                                topology_summary_cfg=hierarchical._topology_summary_config(options),
                                attribute_summary_cfg=hierarchical._attribute_summary_config(options),
                                attr_cfg=attr_cfg,
                                attribute_diffusion_cfg=diffusion_cfg,
                                node_noise=node_noise,
                                bond_noise=bond_noise,
                                generator=validation_generator,
                            )
                            batch_size = batch[0].size(0)
                            validation_sums["loss"] += float(loss) * batch_size
                            for key, value in parts.items():
                                validation_sums[key] += float(value) * batch_size
                            validation_count += batch_size
                    row.update({
                        f"val_{key}": value / max(validation_count, 1)
                        for key, value in validation_sums.items()
                    })
                history.append(row)
                if bool(train_cfg.get("lr_schedule", True)):
                    for scheduler in schedulers:
                        scheduler.step()
                if (
                    epoch == 1
                    or epoch % int(train_cfg.get("log_every", 10)) == 0
                    or epoch == epochs
                ):
                    line = (
                        f"Hybrid-attributed-loggap epoch {epoch}/{epochs} "
                        f"train={row['train_loss']:.6f}"
                        + (
                            f" val={row['val_loss']:.6f}"
                            if "val_loss" in row else ""
                        )
                    )
                    print(line, flush=True)
                    log.write(line + "\n")
                    log.flush()

        checkpoint_path = staging / "checkpoints/gdsm_simple.pt"
        reference_contract = {
            "factorization": "p(A) p(X,R|A)",
            "topology": "combinatorial_laplacian_log_gap_VP_diffusion",
            "topology_edge_existence": "spectral_decoder_only",
            "topology_auxiliary": "connected_induced_unattributed_graphlets_k3_k4_k5_plus_ORCA_orbits",
            "attribute_process": "fixed_topology_exact_terminal_marginal_categorical_diffusion",
            "attribute_auxiliary": "connected_induced_typed_graphlets_k3_k4_k5_training_vocabulary_plus_overflow",
            "gradient_routing": "separate_topology_and_attribute_PPGN_encoders",
            "node_categories": "iterative_marginal_categorical_diffusion",
            "edge_categories": "iterative_real_bond_diffusion_on_fixed_present_edges_only",
            "edge_head_includes_no_edge": False,
            "attribute_time_conditioning": True,
            "categorical_posterior": "clean_endpoint_mixture_exact_skip_posterior",
            "endpoint_constraints": "degree_compatible_atoms_plus_joint_valence_budget",
            "rewiring": False,
            "posthoc_repair": False,
        }
        state = {
            "attribute_diffusion_training_contract": ATTRIBUTE_DIFFUSION_TRAINING_CONTRACT,
            "architecture_contract": "hierarchical_topology_then_fixed_topology_categorical_attributes_v1",
            "format": CHECKPOINT_FORMAT,
            "variant": str(options["variant"]),
            "model_x_state": {
                key: value.detach().cpu() for key, value in model_x.state_dict().items()
            },
            "model_spectrum_state": {
                key: value.detach().cpu() for key, value in model_lam.state_dict().items()
            },
            "ema_x_state": ema_x.shadow,
            "ema_spectrum_state": ema_lam.shadow,
            "model_config": model_cfg,
            "sde": copy.deepcopy(dict(options["sde"])),
            "sample": copy.deepcopy(dict(options["sample"])),
            "spectral_operator": "combinatorial_laplacian",
            "spectral_transform": hierarchical._jsonable(spectral_transform),
            "max_nodes": max_nodes,
            "basis_adjacencies": train_base[1].numpy(),
            "basis_num_nodes": train_base[3].numpy().astype(np.int64),
            "basis_source": "training_split_only",
            "vocabulary": vocab.to_dict(),
            "topology_summary": {
                "enabled": True,
                "training_config": hierarchical._topology_summary_config(options),
                **topology_meta,
            },
            "attribute_summary": {
                "enabled": True,
                "training_config": hierarchical._attribute_summary_config(options),
                **attribute_meta,
            },
            "attribute_diffusion_config": diffusion_cfg,
            "attribute_diffusion_schema": diffusion_schema,
            "attributed_config": copy.deepcopy(attr_cfg),
            "history": history,
            "train_seed": request.run.train_seed,
            "reference_contract": reference_contract,
        }
        torch.save(state, checkpoint_path)
        resolved = copy.deepcopy(dict(options))
        resolved["model"] = dict(resolved["model"])
        resolved["model"]["max_nodes"] = max_nodes
        resolved["model"]["max_feat_num"] = model_cfg["max_feat_num"]
        (staging / "resolved_config.yaml").write_text(
            yaml.safe_dump({wrapper.model_id: resolved}, sort_keys=False)
        )
        manifest = {
            "attribute_diffusion_training_contract": ATTRIBUTE_DIFFUSION_TRAINING_CONTRACT,
            "architecture_contract": "hierarchical_topology_then_fixed_topology_categorical_attributes_v1",
            "format": TRAINING_FORMAT,
            "model_id": wrapper.model_id,
            "variant": str(options["variant"]),
            "run_id": request.run.run_id,
            "train_seed": request.run.train_seed,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "duration_seconds": time.monotonic() - started,
            "dataset": {
                "benchmark_id": request.dataset.benchmark_id,
                "serialized_id": request.dataset.serialized_id,
                "fingerprint": fingerprint,
                "split_sha256": {
                    key: _sha256(value)
                    for key, value in request.dataset.split_paths.items()
                },
            },
            "options": hierarchical._jsonable(options),
            "checkpoint": {
                "path": "checkpoints/gdsm_simple.pt",
                "sha256": _sha256(checkpoint_path),
            },
            "checkpoint_selection": {
                "kind": "final_configured_epoch",
                "epoch": epochs,
            },
            "reference_contract": reference_contract,
            "parameter_counts": {
                "node_diffusion": sum(p.numel() for p in model_x.parameters()),
                "topology_branch": sum(
                    p.numel() for p in model_lam.topology_parameters()
                ),
                "attribute_branch": sum(
                    p.numel() for p in model_lam.attribute_parameters()
                ),
            },
            "test_used_for_training": False,
        }
        _write_json(staging / "manifest.json", manifest)
        if layout.train_dir.exists():
            shutil.rmtree(layout.train_dir)
        staging.replace(layout.train_dir)
        _write_json(
            layout.run_manifest_path,
            {
                "format": "grapher_baseline_run_v1",
                "model_id": wrapper.model_id,
                "dataset_id": request.run.dataset_id,
                "run_id": request.run.run_id,
                "train_seed": request.run.train_seed,
            },
        )
        return _artifacts(wrapper, request)
    except BaseException:
        shutil.rmtree(staging, ignore_errors=True)
        raise


def _sampling_times(total_steps: int, sample_steps: int) -> list[int]:
    if sample_steps < 1 or sample_steps > total_steps:
        raise ValueError("attribute sample_steps must be in [1, total_steps]")
    times = np.rint(np.linspace(total_steps, 0, sample_steps + 1)).astype(int).tolist()
    if times[0] != total_steps or times[-1] != 0:
        raise AssertionError("attribute sampling schedule endpoints are incorrect")
    if any(next_time >= time for time, next_time in zip(times, times[1:])):
        raise ValueError("attribute sampling schedule must strictly decrease")
    return times


def _initial_attribute_state(
    flags: torch.Tensor,
    support: torch.Tensor,
    node_noise: MarginalNoise,
    bond_noise: MarginalNoise,
    generator: torch.Generator,
) -> tuple[torch.Tensor, torch.Tensor]:
    b, n = flags.shape
    node_probs = node_noise.marginal.view(1, 1, -1).expand(b, n, -1)
    nodes = draw_categories(node_probs, generator).masked_fill(~flags.bool(), 0)
    edge_probs = bond_noise.marginal.view(1, 1, 1, -1).expand(
        b, n, n, -1
    )
    bonds = _sample_upper_categories(edge_probs, support, generator)
    return nodes, bonds


def _reverse_fixed_bonds(
    clean_probs: torch.Tensor,
    current: torch.Tensor,
    support: torch.Tensor,
    noise: MarginalNoise,
    t: torch.Tensor,
    s: torch.Tensor,
    generator: torch.Generator,
) -> tuple[torch.Tensor, torch.Tensor]:
    if clean_probs.shape[:-1] != support.shape:
        raise ValueError("Bond clean probabilities and support differ")
    posterior = torch.zeros_like(clean_probs)
    if bool(support.any()):
        tv = t[:, None, None].expand_as(current)[support]
        sv = s[:, None, None].expand_as(current)[support]
        posterior[support] = noise.reverse_probs(
            clean_probs[support], current[support], tv, sv
        )
    return _sample_upper_categories(posterior, support, generator), posterior


def _attribute_diffusion_decode(
    model: HybridAttributedSpectrumPPGNScore,
    topology: torch.Tensor,
    flags: torch.Tensor,
    sizes: torch.Tensor,
    spectral_transform: Mapping[str, Any],
    vocab: GraphCategoryVocabulary,
    attributed_cfg: Mapping[str, Any],
    diffusion_cfg: Mapping[str, Any],
    diffusion_schema: Mapping[str, Any],
    *,
    generator: torch.Generator,
) -> tuple[
    torch.Tensor,
    torch.Tensor,
    dict[str, torch.Tensor],
    list[dict[str, Any]],
    list[list[dict[str, Any]]],
]:
    device = topology.device
    b, n, _ = topology.shape
    support = topology.bool()
    clean_x = degree_features(
        topology.to(torch.float32), flags, model.max_feat_num
    )
    clean_lam, clean_u = _laplacian_eigh_padded(
        topology.to(torch.float32), sizes.to(torch.long)
    )
    clean_state = _operator_eigenvalues_to_spectral_state(
        clean_lam,
        flags,
        spectral_operator="combinatorial_laplacian",
        spectral_transform=spectral_transform,
    )
    schedule, node_noise, bond_noise = _attribute_noise_models(
        diffusion_schema, diffusion_cfg, device
    )
    times = _sampling_times(
        int(diffusion_cfg["steps"]),
        int(diffusion_cfg.get("sample_steps", diffusion_cfg["steps"])),
    )
    node_state, bond_state = _initial_attribute_state(
        flags, support, node_noise, bond_noise, generator
    )
    per_graph = [
        {
            "attribute_reverse_steps": len(times) - 1,
            "node_category_change_count": 0,
            "bond_category_change_count": 0,
            "topology_preserved": True,
        }
        for _ in range(b)
    ]
    trajectories: list[list[dict[str, Any]]] = [[] for _ in range(b)]
    final_output: dict[str, torch.Tensor] | None = None
    endpoint_node_posterior: torch.Tensor | None = None
    endpoint_bond_posterior: torch.Tensor | None = None
    atom_masks: torch.Tensor | None = None
    bond_rows: list[dict[str, Any]] | None = None

    for current_time, next_time in zip(times, times[1:]):
        t = torch.full((b,), current_time, dtype=torch.long, device=device)
        s = torch.full((b,), next_time, dtype=torch.long, device=device)
        node_input, edge_input = model.categorical_attribute_inputs(
            flags, support, node_state, bond_state
        )
        output = model.forward_attributes(
            clean_x,
            topology.to(torch.float32),
            flags,
            clean_u,
            clean_state,
            node_attr=node_input,
            edge_attr=edge_input,
            attribute_time=t.to(torch.float32) / float(diffusion_cfg["steps"]),
        )
        clean_node_probs = torch.softmax(output["node_logits"], dim=-1)
        clean_bond_probs = torch.softmax(output["edge_logits"], dim=-1)
        node_posterior = node_noise.reverse_probs(
            clean_node_probs, node_state, t[:, None].expand_as(node_state),
            s[:, None].expand_as(node_state)
        )
        if next_time > 0:
            new_nodes = draw_categories(node_posterior, generator).masked_fill(
                ~flags.bool(), 0
            )
            new_bonds, _ = _reverse_fixed_bonds(
                clean_bond_probs,
                bond_state,
                support,
                bond_noise,
                t,
                s,
                generator,
            )
        else:
            # Exact categorical posterior first, then the intrinsic constrained
            # endpoint sampler.  The constraints cannot modify topology.
            _, endpoint_bond_posterior = _reverse_fixed_bonds(
                clean_bond_probs,
                bond_state,
                support,
                bond_noise,
                t,
                s,
                generator,
            )
            endpoint_node_posterior = node_posterior
            decode_cfg = dict(attributed_cfg.get("decode", {}) or {})
            validate_decode_config(
                decode_cfg,
                vocab.node_values,
                vocab.edge_values,
                node_attribute=vocab.node_attribute,
                edge_attribute=vocab.edge_attribute,
            )
            new_nodes, atom_masks = sample_atoms(
                torch.log(node_posterior.clamp_min(1.0e-30)),
                support,
                flags,
                vocab.node_values,
                decode_cfg,
                generator,
            )
            new_bonds, bond_rows = sample_bonds(
                torch.log(endpoint_bond_posterior.clamp_min(1.0e-30)),
                support,
                flags,
                new_nodes,
                vocab.node_values,
                vocab.edge_values,
                decode_cfg,
                generator,
            )
        node_changes = ((new_nodes != node_state) & flags.bool()).sum(dim=1)
        bond_changes = (
            (new_bonds != bond_state)
            & support
            & torch.ones_like(support).triu(1)
        ).sum(dim=(1, 2))
        for row_index in range(b):
            per_graph[row_index]["node_category_change_count"] += int(
                node_changes[row_index]
            )
            per_graph[row_index]["bond_category_change_count"] += int(
                bond_changes[row_index]
            )
            if bool(diffusion_cfg.get("save_trajectory", False)):
                trajectories[row_index].append({
                    "from_t": int(current_time),
                    "to_t": int(next_time),
                    "node_categories": new_nodes[row_index].detach().cpu().tolist(),
                    "bond_categories": new_bonds[row_index].detach().cpu().tolist(),
                })
        node_state, bond_state = new_nodes, new_bonds
        final_output = output

    if final_output is None or endpoint_node_posterior is None or endpoint_bond_posterior is None:
        raise AssertionError("Attribute diffusion did not reach the clean endpoint")
    if atom_masks is None or bond_rows is None:
        raise AssertionError("Endpoint constraints were not evaluated")
    endpoint_rows = decoding_diagnostics(
        support,
        flags,
        node_state,
        bond_state,
        vocab.node_values,
        vocab.edge_values,
        atom_masks,
        bond_rows,
    )
    for row, endpoint in zip(per_graph, endpoint_rows):
        row.update(endpoint)
        row["attribute_diffusion_steps"] = int(diffusion_cfg["steps"])
        row["attribute_sampling_steps"] = len(times) - 1
        row["edge_head_includes_no_edge"] = False
        row["endpoint_constraint"] = "final_reverse_transition"

    # A final clean-state pass provides summary predictions conditioned on the
    # actually serialized categories.  It does not resample or modify anything.
    final_node_input, final_edge_input = model.categorical_attribute_inputs(
        flags, support, node_state, bond_state
    )
    final_output = model.forward_attributes(
        clean_x,
        topology.to(torch.float32),
        flags,
        clean_u,
        clean_state,
        node_attr=final_node_input,
        edge_attr=final_edge_input,
        attribute_time=torch.zeros((b,), device=device),
    )
    final_output["endpoint_node_posterior"] = endpoint_node_posterior
    final_output["endpoint_bond_posterior"] = endpoint_bond_posterior
    return node_state, bond_state, final_output, per_graph, trajectories


def generate(
    wrapper,
    request: GenerateRequest,
    state: Mapping[str, Any],
    manifest: Mapping[str, Any],
    options: Mapping[str, Any],
) -> GenerationArtifacts:
    del manifest
    validate_options(options)
    if state.get("format") != CHECKPOINT_FORMAT:
        raise RuntimeError(
            f"Expected {CHECKPOINT_FORMAT}, found {state.get('format')!r}"
        )
    if (
        state.get("attribute_diffusion_training_contract")
        != ATTRIBUTE_DIFFUSION_TRAINING_CONTRACT
    ):
        raise RuntimeError("Checkpoint does not satisfy the hybrid attribute contract")
    layout = request.run.layout
    target = layout.generation_dir(request.resolved_generation_id)
    ArtifactLayout.require_available(target, overwrite=request.overwrite)
    if request.num_graphs < 1:
        raise ValueError("num_graphs must be positive")
    batch_size = int(options.get("generation_batch_size", 128))
    if batch_size < 1:
        raise ValueError("generation_batch_size must be positive")
    device = _resolve_device(options.get("runtime", {}))
    _seed_everything(request.generation_seed)
    vocab = GraphCategoryVocabulary.from_dict(dict(state["vocabulary"]))
    model_x, model_lam = _build_models(
        dict(state["model_config"]),
        dict(state["topology_summary"]),
        dict(state["attribute_summary"]),
        device,
    )
    use_ema = bool(options.get("sample", {}).get("use_ema", False))
    model_x.load_state_dict(state["ema_x_state" if use_ema else "model_x_state"])
    model_lam.load_state_dict(
        state["ema_spectrum_state" if use_ema else "model_spectrum_state"]
    )
    model_x.eval()
    model_lam.eval()
    sde_x, sde_lam = _make_sdes({"sde": state["sde"]}, device)
    sample_cfg = copy.deepcopy(dict(state["sample"]))
    sample_cfg.update(dict(options.get("sample", {})))
    separate_rng = bool(sample_cfg.get("separate_attribute_rng", True))
    rng, topology_generator, attribute_generator, attribute_seed = (
        hierarchical._generation_rngs(
            request.generation_seed, device, separate_rng
        )
    )
    basis_adj = torch.tensor(
        np.asarray(state["basis_adjacencies"]), dtype=torch.float32
    )
    basis_n = torch.tensor(
        np.asarray(state["basis_num_nodes"]), dtype=torch.long
    )
    spectral_transform = dict(state["spectral_transform"])
    threshold = float(sample_cfg.get("threshold", 0.5))
    attr_cfg = copy.deepcopy(dict(state["attributed_config"]))
    runtime_attr = dict(options.get("attributed", {}) or {})
    if "decode" in runtime_attr:
        attr_cfg["decode"] = _deep_update(
            dict(attr_cfg.get("decode", {}) or {}),
            dict(runtime_attr.get("decode", {}) or {}),
        )
    validate_decode_config(
        dict(attr_cfg.get("decode", {}) or {}),
        vocab.node_values,
        vocab.edge_values,
        node_attribute=vocab.node_attribute,
        edge_attribute=vocab.edge_attribute,
    )
    diffusion_cfg = copy.deepcopy(dict(state["attribute_diffusion_config"]))
    runtime_diffusion = dict(options.get("attribute_diffusion", {}) or {})
    for key in ("sample_steps", "save_trajectory"):
        if key in runtime_diffusion:
            diffusion_cfg[key] = runtime_diffusion[key]
    if int(diffusion_cfg.get("sample_steps", 0)) > int(diffusion_cfg["steps"]):
        raise ValueError("attribute_diffusion.sample_steps cannot exceed trained steps")
    diffusion_schema = dict(state["attribute_diffusion_schema"])

    graphs: list[nx.Graph] = []
    topology_graphs: list[nx.Graph] = []
    continuous: list[np.ndarray] = []
    spectra: list[np.ndarray] = []
    basis_indices: list[int] = []
    topology_predictions: list[dict[str, Any]] = []
    typed_predictions: list[dict[str, Any]] = []
    combined_predictions: list[dict[str, Any]] = []
    attribute_rows: list[dict[str, Any]] = []
    topology_hashes: list[str] = []
    trajectories: list[list[dict[str, Any]]] = []
    started = time.monotonic()

    with torch.no_grad():
        while len(graphs) < request.num_graphs:
            b = min(batch_size, request.num_graphs - len(graphs))
            indices = rng.integers(0, len(basis_adj), size=b)
            donor_adj = basis_adj[indices]
            donor_n = basis_n[indices]
            sample_x, soft, lam, u = sample_batch(
                model_x,
                model_lam,
                donor_adjacencies=donor_adj,
                donor_sizes=donor_n,
                sde_x=sde_x,
                sde_lam=sde_lam,
                sample_cfg=sample_cfg,
                eigen_mask_mode="laplacian_nonzero_prefix",
                spectral_operator="combinatorial_laplacian",
                spectral_transform=spectral_transform,
                device=device,
                generator=topology_generator,
            )
            soft = 0.5 * (soft + soft.transpose(-1, -2))
            nmax = soft.size(1)
            flags = (
                torch.arange(nmax, device=device).unsqueeze(0)
                < donor_n.to(device).unsqueeze(1)
            ).float()
            topology_state = _operator_eigenvalues_to_spectral_state(
                lam,
                flags,
                spectral_operator="combinatorial_laplacian",
                spectral_transform=spectral_transform,
            )
            eye = torch.eye(nmax, device=device, dtype=torch.bool).unsqueeze(0)
            discrete = (
                (soft > threshold)
                & ~eye
                & flags.bool().unsqueeze(1)
                & flags.bool().unsqueeze(2)
            )
            discrete = discrete | discrete.transpose(1, 2)
            state_hashes = [
                hierarchical._tensor_state_digest(
                    sample_x[row],
                    soft[row],
                    flags[row],
                    u[row],
                    topology_state[row],
                    lam[row],
                    discrete[row],
                )
                for row in range(b)
            ]
            topology_out = model_lam.forward_topology(
                sample_x, soft, flags, u, topology_state
            )
            (
                node_index,
                edge_index,
                attribute_out,
                batch_attribute_rows,
                batch_trajectories,
            ) = _attribute_diffusion_decode(
                model_lam,
                discrete,
                flags,
                donor_n.to(device),
                spectral_transform,
                vocab,
                attr_cfg,
                diffusion_cfg,
                diffusion_schema,
                generator=attribute_generator,
            )
            for row in range(b):
                if state_hashes[row] != hierarchical._tensor_state_digest(
                    sample_x[row],
                    soft[row],
                    flags[row],
                    u[row],
                    topology_state[row],
                    lam[row],
                    discrete[row],
                ):
                    raise AssertionError("Attribute diffusion modified topology-generation inputs")

            topology_summaries = model_lam.topology_structure_means_from_outputs(
                topology_out
            )
            typed_summaries = model_lam.attribute_structure_means_from_outputs(
                attribute_out
            )
            endpoint_node_posterior = attribute_out["endpoint_node_posterior"]
            endpoint_bond_posterior = attribute_out["endpoint_bond_posterior"]

            for row in range(b):
                size = int(donor_n[row])
                topology_matrix = discrete[row, :size, :size]
                topology_graph = nx.from_numpy_array(
                    topology_matrix.cpu().numpy().astype(np.int8)
                )
                graph = nx.Graph()
                for node in range(size):
                    graph.add_node(
                        node,
                        **{
                            str(vocab.node_attribute): vocab.node_value(
                                int(node_index[row, node])
                            )
                        },
                    )
                upper = topology_matrix.triu(1).nonzero(as_tuple=False)
                for left, right in upper.tolist():
                    graph.add_edge(
                        int(left),
                        int(right),
                        **{
                            str(vocab.edge_attribute): vocab.edge_value(
                                int(edge_index[row, left, right]) + 1
                            )
                        },
                    )
                if set(graph.edges()) != set(topology_graph.edges()):
                    raise AssertionError("Serialized attributed graph differs from fixed topology")

                index = int(indices[row])
                graph_index = len(graphs)
                diagnostic = batch_attribute_rows[row]
                diagnostic.update({
                    "graph_index": graph_index,
                    "node_confidence_mean": float(
                        endpoint_node_posterior[row, :size].max(-1).values.mean().cpu()
                    ),
                    "edge_confidence_mean": (
                        float(
                            endpoint_bond_posterior[row, :size, :size][
                                topology_matrix
                            ].max(-1).values.mean().cpu()
                        )
                        if bool(topology_matrix.any()) else None
                    ),
                    "connected": nx.is_connected(topology_graph),
                    "topology_state_sha256": state_hashes[row],
                    "posthoc_repair": False,
                    "rewiring": False,
                })
                graph.graph["attribute_diffusion"] = {
                    "steps": int(diffusion_cfg["steps"]),
                    "sample_steps": int(diffusion_cfg["sample_steps"]),
                    "constraint_mode": str(
                        attr_cfg.get("decode", {}).get("constraint_mode", "none")
                    ),
                    "topology_state_sha256": state_hashes[row],
                    "edge_head_includes_no_edge": False,
                    "posthoc_repair": False,
                }
                graphs.append(graph)
                topology_graphs.append(topology_graph)
                matrix = soft[row, :size, :size].cpu().numpy().astype(np.float64)
                np.fill_diagonal(matrix, 0)
                continuous.append(matrix)
                spectra.append(lam[row].cpu().numpy().astype(np.float64))
                basis_indices.append(index)
                topology_hashes.append(state_hashes[row])
                attribute_rows.append(diagnostic)
                if bool(diffusion_cfg.get("save_trajectory", False)):
                    trajectories.append(batch_trajectories[row])

                topology_prediction = {
                    "graph_index": graph_index,
                    **{
                        key: value[row].cpu().numpy().astype(np.float64)
                        for key, value in topology_summaries.items()
                    },
                }
                typed_prediction = {
                    "graph_index": graph_index,
                    **{
                        key: value[row].cpu().numpy().astype(np.float64)
                        for key, value in typed_summaries.items()
                    },
                }
                topology_predictions.append(topology_prediction)
                typed_predictions.append(typed_prediction)
                combined_predictions.append({
                    "graph_index": graph_index,
                    **{
                        f"topology_{key}": value
                        for key, value in topology_prediction.items()
                        if key != "graph_index"
                    },
                    **{
                        key: value
                        for key, value in typed_prediction.items()
                        if key != "graph_index"
                    },
                })
            print(
                f"Hybrid-attributed-loggap generated {len(graphs)}/{request.num_graphs}",
                flush=True,
            )

    aggregate: dict[str, Any] = {
        "num_requested": request.num_graphs,
        "num_generated": len(graphs),
        "num_filtered": 0,
        "num_topology_resampled": 0,
        "attribute_diffusion_steps": int(diffusion_cfg["steps"]),
        "attribute_sampling_steps": int(diffusion_cfg["sample_steps"]),
        "node_confidence_mean": float(
            np.mean([row["node_confidence_mean"] for row in attribute_rows])
        ),
        "constraint_mode": attr_cfg.get("decode", {}).get("constraint_mode", "none"),
        "edge_head_includes_no_edge": False,
    }
    finite_edge = [
        row["edge_confidence_mean"]
        for row in attribute_rows
        if row["edge_confidence_mean"] is not None
    ]
    aggregate["edge_confidence_mean"] = (
        float(np.mean(finite_edge)) if finite_edge else None
    )
    for key in (
        "topology_infeasible",
        "atom_degree_incompatible",
        "bond_valence_exceeded",
        "capacity_constraints_satisfied",
        "topology_preserved",
        "connected",
    ):
        values = [bool(row[key]) for row in attribute_rows if key in row]
        aggregate[key + "_count"] = sum(values)
        aggregate[key + "_denominator"] = len(values)
        aggregate[key + "_rate"] = float(np.mean(values)) if values else None
    for key in (
        "atom_constraint_activations",
        "bond_constraint_activations",
        "node_category_change_count",
        "bond_category_change_count",
    ):
        aggregate[key] = int(sum(int(row.get(key, 0)) for row in attribute_rows))

    target.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(
        tempfile.mkdtemp(prefix=".gdsm_hybrid_attr_generate_", dir=target.parent)
    )
    try:
        payloads: dict[str, Any] = {
            "base_graphs": graphs,
            "molecular_graphs": graphs,
            "topology_graphs": topology_graphs,
            "continuous_adjacencies": continuous,
            "sampled_spectra": spectra,
            "sampled_basis_indices": basis_indices,
            "predicted_topology_summaries": topology_predictions,
            "predicted_typed_graphlet_summaries": typed_predictions,
            "predicted_structure_summaries": combined_predictions,
        }
        if bool(diffusion_cfg.get("save_trajectory", False)):
            payloads["attribute_diffusion_trajectories"] = trajectories
        files: dict[str, dict[str, Any]] = {}
        for name, data in payloads.items():
            path = staging / (name + ".pkl")
            with path.open("wb") as handle:
                pickle.dump(data, handle, protocol=pickle.HIGHEST_PROTOCOL)
            files[name] = {"path": path.name, "sha256": _sha256(path)}
        files["base_graphs"]["role"] = "final_attributed_graphs"
        files["molecular_graphs"]["role"] = "compatibility_alias"
        files["topology_graphs"]["role"] = "fixed_binary_topologies_before_attributes"
        files["predicted_topology_summaries"].update({
            "topology_only_graphlets": True,
            "orbit_summary": bool(state["topology_summary"].get("orbit_enabled", False)),
        })
        files["predicted_typed_graphlet_summaries"]["typed_graphlets"] = True
        files["predicted_structure_summaries"]["role"] = (
            "combined_hierarchical_predictions"
        )
        diagnostics_path = staging / "attribute_diffusion_diagnostics.json"
        _write_json(
            diagnostics_path,
            {"per_graph": attribute_rows, "aggregate": aggregate},
        )
        pairing_path = staging / "topology_pairing.json"
        _write_json(
            pairing_path,
            {
                "format": "gdsm_hybrid_attributed_topology_pairing_v1",
                "hash_inputs": [
                    "sample_x",
                    "soft_adjacency",
                    "flags",
                    "eigenbasis",
                    "spectral_state",
                    "eigenvalues",
                    "binary_topology",
                ],
                "per_graph_sha256": topology_hashes,
                "batch_size": batch_size,
                "generation_seed": request.generation_seed,
                "checkpoint_sha256": _sha256(request.checkpoint_path),
            },
        )
        files["attribute_diffusion_diagnostics"] = {
            "path": diagnostics_path.name,
            "sha256": _sha256(diagnostics_path),
        }
        files["topology_pairing"] = {
            "path": pairing_path.name,
            "sha256": _sha256(pairing_path),
        }
        _write_json(
            staging / "manifest.json",
            {
                "format": GENERATION_FORMAT,
                "model_id": wrapper.model_id,
                "variant": state["variant"],
                "run_id": request.run.run_id,
                "generation_id": request.resolved_generation_id,
                "generation_seed": request.generation_seed,
                "num_requested": request.num_graphs,
                "num_generated": len(graphs),
                "num_filtered": 0,
                "num_topology_resampled": 0,
                "duration_seconds": time.monotonic() - started,
                **files,
                "attribute_diffusion_training_contract": state.get(
                    "attribute_diffusion_training_contract"
                ),
                "architecture_contract": state.get("architecture_contract"),
                "checkpoint": {
                    "path": str(request.checkpoint_path.resolve()),
                    "sha256": _sha256(request.checkpoint_path),
                },
                "sampling": {
                    "factorization": "p(A) p(X,R|A)",
                    "topology": "Laplacian_log_gap_reverse_diffusion",
                    "topology_auxiliary_supervision": [
                        "topology_only_connected_induced_graphlets_k3_k4_k5",
                        "ORCA_orbit_histogram_and_log_total",
                    ],
                    "attribute_process": "fixed_topology_marginal_categorical_reverse_diffusion",
                    "attribute_diffusion_steps": int(diffusion_cfg["steps"]),
                    "attribute_sampling_steps": int(diffusion_cfg["sample_steps"]),
                    "attribute_schedule": "cosine_exact_terminal",
                    "categorical_posterior": "clean_endpoint_mixture_exact_skip_posterior",
                    "attribute_auxiliary_supervision": "typed_connected_induced_graphlets_k3_k4_k5",
                    "topology_attribute_encoder_sharing": False,
                    "edge_attributes": "real_bond_type_diffusion_on_generated_edges_only",
                    "edge_head_includes_no_edge": False,
                    "topology_graphlet_supervision": True,
                    "typed_graphlet_supervision": True,
                    "endpoint_constraint": "final_reverse_transition",
                    "node_decode_mode": attr_cfg.get("decode", {}).get(
                        "node_mode", "sample"
                    ),
                    "edge_decode_mode": attr_cfg.get("decode", {}).get(
                        "edge_mode", "sample"
                    ),
                    "node_temperature": float(
                        attr_cfg.get("decode", {}).get("node_temperature", 1.0)
                    ),
                    "edge_temperature": float(
                        attr_cfg.get("decode", {}).get("edge_temperature", 0.6)
                    ),
                    "constraint_mode": attr_cfg.get("decode", {}).get(
                        "constraint_mode", "atom_bond_valence"
                    ),
                    "edge_order": attr_cfg.get("decode", {}).get(
                        "edge_order", "random"
                    ),
                    "infeasible_policy": attr_cfg.get("decode", {}).get(
                        "infeasible_policy", "retain"
                    ),
                    "separate_attribute_rng": separate_rng,
                    "topology_seed": request.generation_seed,
                    "attribute_seed": attribute_seed,
                    "generation_batch_size": batch_size,
                    "topology_preserved_during_attribute_diffusion": True,
                    "degree_sequence_prescribed_during_topology_diffusion": False,
                    "connectivity_guaranteed": False,
                    "full_chemical_validity_guaranteed": False,
                    "rewiring": False,
                    "posthoc_repair": False,
                    "filtering": False,
                    "replacement_sampling": False,
                },
            },
        )
        if target.exists():
            shutil.rmtree(target)
        staging.replace(target)
    except BaseException:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    return GenerationArtifacts(
        run_dir=layout.run_dir,
        generation_dir=target,
        graphs_path=target / "base_graphs.pkl",
        manifest_path=target / "manifest.json",
        num_requested=request.num_graphs,
        num_generated=len(graphs),
        graphs_sha256=_sha256(target / "base_graphs.pkl"),
    )
