[[datasets]]
type = "planar"
count = 500
nodes = 64
edges = 181

[[datasets]]
type = "sbm"
count = 500
nodes = 100
block_sizes = [25, 25, 25, 25]
probabilities = [[0.25, 0.05, 0.05, 0.05],
                 [0.05, 0.25, 0.05, 0.05],
                 [0.05, 0.05, 0.25, 0.05],
                 [0.05, 0.05, 0.05, 0.25]]

[[datasets]]
type = "ego"
max_node = 399
min_node = 50
hop = 3

[[datasets]]
type = "qm9"

[[datasets]]
type = "zinc"