[[datasets]]
type = "planar"
count = 500
nodes = 500
edges = 1575

[[datasets]]
type = "sbm"
count = 500
nodes = 361
block_sizes = [25, 25, 25, 25]
probabilities = [[0.25, 0.05, 0.05, 0.05],
                 [0.05, 0.25, 0.05, 0.05],
                 [0.05, 0.05, 0.25, 0.05],
                 [0.05, 0.05, 0.05, 0.25]]

[[datasets]]
type = "ego"
count = 200
max_node = 18
min_node = 4


[[datasets]]
type = "qm9"

[[datasets]]
type = "zinc"


[[datasets]]
type = "community"
count = 200
min_node = 12
max_node = 20
p_intra = 0.3
p_inter = 0.05


[[datasets]]
type = "grid"
count = 100
min_node = 4
max_node = 20