[training]
learning_rate = 0.001    # Learning rate for the optimizer
hidden_dim = 64          # Hidden dimension size
batch_size = 8					 # Batch size
num_layer = 5					   # GIN layer
T = 1
k_eigen = 8

[guided_rewiring]
ensure_connected = 1
k_hop = 2
energy_weight = 0.1
dist_name = 'netlsd'


[energy]
steps_per_graph = 1
learning_rate = 0.001
hidden_dim = 256
num_layers = 3
dropout = 0.1
tau = 0.2
grad_clip = 1.0
l2_reg = 0.0

[inference]
generate_samples = 200    # Number of samples to generate
