[training]
num_epochs = 5000     # Number of training epochs
learning_rate = 0.001    # Learning rate for the optimizer
hidden_dim = 64          # Hidden dimension size
batch_size = 1					 # Batch size
num_layer = 5					   # GIN layer
epsilon = 0.0001
T = 1000

[inference]
generate_samples = 200    # Number of samples to generate
