[training]
num_epochs = 200     # Number of training epochs
learning_rate = 0.0003    # Learning rate for the optimizer
hidden_dim = 64          # Hidden dimension size
batch_size = 1					 # Batch size
num_layer = 5					   # GIN layer
epsilon = 0.0001
beta_kl = 0.000
gamma_lap = 0.0001
gamma_local = 0.0001
T = 100
cycle = 4

[data]
k_eigen = 15

[inference]
threshold = 0.01
generate_samples = 200    # Number of samples to generate
