[training]
num_epochs = 400     # Number of training epochs
learning_rate = 0.001    # Learning rate for the optimizer
hidden_dim = 32          # Hidden dimension size
latent_dim = 16          # Latent dimension size
batch_size = 4					 # Batch size
num_layer = 4
T = 1000


[inference]
generate_samples = 200    # Number of samples to generate
