[training]
num_epochs = 200     # Number of training epochs
learning_rate = 0.001    # Learning rate for the optimizer
hidden_dim = 32          # Hidden dimension size
latent_dim = 16          # Latent dimension size
batch_size = 4					 # Batch size
warmup_epochs = 100			 # Warm up epoch

[training.weights]
reconstruction = 1.0     # Weight for reconstruction loss
kl_divergence = 1.0     # Weight for KL divergence loss
erdos_gallai = 0.05       # Weight for Erdős-Gallai loss

[inference]
generate_samples = 200    # Number of samples to generate
